# Generated by Django 2.2.28 on 2025-05-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0008_auto_20211005_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('TW', 'Town'), ('CT', 'City'), ('PR', 'Province')], default='TW', max_length=2),
        ),
    ]
